### ISSUE TITLE
[TicTacToe] Тела пропертей

### ISSUE THREAD

**Issue by pavel-b-novikov** [ask705/nsudotnet#1]
```public Cell[,] Cells { get => cells; set => cells = value; }```

Что это? И зачем?

**Comment by ask705** [comment]
Студия предложила сделать свойство - я сделал

**Comment by pavel-b-novikov** [comment]
Удивительно как вам студия не предложила сделать авто-проперть. Хотя.. это не входит в обяанности студии, верно?

**Comment by pavel-b-novikov** [comment]
Переделайте на нормальные авто-проперти там, где это уместно. 
И да - перестаньте уведомлять об изменении приватных полей.
