### ISSUE TITLE
[TicTacToe] CheckOnWin

### ISSUE THREAD

**Issue by pavel-b-novikov** [ask705/nsudotnet#2]
То есть вы полностью скопировали код для определения победы/поражения? Вы что курили?

**Comment by ask705** [comment]
Скопировал, потому что в LadgeField метод работает c cells(cell[,]) из FieldCell, а так работает с cells(FiledCell[,])
Я думал, что при наследовании, при покрытии поля cells, оно заменится новым из производного класса, но оказалось, что нет.

**Comment by pavel-b-novikov** [comment]
А то есть абстракцию выделить (интерфейс) - нет? Не могем?

**Comment by ask705** [comment]
Ну так если выделять интерфейс, нужно будет с каждой реализацией по-новому реализовывать методы. Я же хотел только один раз написать и наследовать реализацию в духе ооп. Получилось не так как я планировал

**Comment by pavel-b-novikov** [comment]
Саму ячейку что мешает выкинуть в интерфейс? С одной пропертью - крестиком или ноликом, который стоит в ней.
