### ISSUE TITLE
[TicTacToe] StubStateCellChangedEnent

### ISSUE THREAD

**Issue by pavel-b-novikov** [ask705/nsudotnet#4]
```static void StubStateCellChangedEnent(StateCell state) { }```

А это что? Чтобы событие на null не проверять? Говнокод чистой воды

**Comment by ask705** [comment]
Это заглушка для event, иначе event == null и когда при изменении состояния свойства я вызываю этот event - выдаёт ошибку обращения к нулевому указателю.

**Comment by pavel-b-novikov** [comment]
Это я и сам знаю. Вы или событие перегрузите (add/remove), или честно проверяйте при триггеринге события
