### ISSUE TITLE
[TicTacToe] Создание вью-моделей

### ISSUE THREAD

**Issue by pavel-b-novikov** [ask705/nsudotnet#6]
``` GameField = new LargeFieldViewModel(ladgeField);```

Я что - на лекции - тихо объяснял чтоли про создание view-моделей из new? Зачем вам контейнер тогда? В текущей реализации контейнер не используется в принципе. Вы не смогли его вырезать потому что не понимаете как, ни смогли его использовать потому что опять же - не понимаете как.

**Comment by ask705** [comment]
Я вроде бы не использовал контейнеры, в этой задачи они лишние - лишь усложняют код

**Comment by pavel-b-novikov** [comment]
Да ну? А в бутстраппере у вас что написано?
