### ISSUE TITLE
[TicTacToe] Дзен-код

### ISSUE THREAD

**Issue by pavel-b-novikov** [ask705/nsudotnet#7]
Задача просто кишит дзен-кодом

```protected int n = 3;``` и ниже ```new protected int n = 3;```

Ощущение, что вы писали это вообще не отдавая себе отчет в том, что происходит в коде

**Comment by ask705** [comment]
Я ввёл параметры для возможного расширения программы. Наверное, перемудрил и плохо расписал имена, виноват
